using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class SaveMenu : DefaultWindow
    {
        public SaveMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

        }
    }
}
